
# Markov Module for Data Communication
----------------------------------------------------
Author: Olaitan Olawale Samuel

Department: Electronics and Computer Enginerring, Lagos State Unniversity

Matric: 220211207

Course Code: ECE 413

Course Title: Data Communication

Lecturer: Dr. Akinyemi


This module models a simple Markov process used in data communication,
where system messages or states follow probabilistic transitions.

In [ ]:
import random
import numpy as np


In [ ]:
# -------------------------------------------------------
# 1️⃣ Create Transition Matrix (General or Custom)
# -------------------------------------------------------
def create_transition_matrix(N=5, self_prob=0.6, next_prob=0.4):
    """
    Create an NxN transition matrix where each state
    has a 'self_prob' chance to remain and a 'next_prob'
    chance to move to the next state cyclically.
    """
    P = np.zeros((N, N))
    for i in range(N):
        P[i, i] = self_prob
        P[i, (i + 1) % N] = next_prob
    return P


In [ ]:
# -------------------------------------------------------
# 2️⃣ Validate Matrix
# -------------------------------------------------------
def validate_matrix(P):
    """
    Ensure matrix is row-stochastic (each row sums to 1).
    """
    for i, row in enumerate(P):
        s = np.sum(row)
        if not np.isclose(s, 1.0):
            raise ValueError(f"Row {i} does not sum to 1 (sum={s})")
    print("✅ Transition matrix validated successfully.")


In [ ]:

# -------------------------------------------------------
# 3️⃣ Compute Stationary Distribution (Power Method)
# -------------------------------------------------------
def compute_stationary_distribution(P, tol=1e-8, max_iter=10000):
    """
    Compute stationary distribution π such that πP = π.
    Uses iterative power method (repeated multiplication).
    """
    N = len(P)
    pi = np.ones(N) / N  # start with uniform
    for _ in range(max_iter):
        new_pi = np.dot(pi, P)
        if np.linalg.norm(new_pi - pi) < tol:
            break
        pi = new_pi
    return pi / np.sum(pi)


In [ ]:
# -------------------------------------------------------
# 4️⃣ Simulation of the Markov Chain
# -------------------------------------------------------
def simulate_markov_chain(P, steps=10000, initial_state=0):
    """
    Simulate the chain for a given number of steps and
    record how often each state is visited.
    """
    N = len(P)
    state = initial_state
    visits = np.zeros(N)

    for _ in range(steps):
        visits[state] += 1
        state = np.random.choice(range(N), p=P[state])

    empirical = visits / np.sum(visits)
    return empirical, visits


In [ ]:
# -------------------------------------------------------
# 5️⃣ Main Test Function
# -------------------------------------------------------
def test_markov_module(N=5, steps=50000):
    """
    Bring all components together.
    Creates a Markov model, validates, computes stationary
    distribution, simulates, and compares results.
    """
    print(f"\n🧮 Running Markov Model with {N} states/messages\n")

    # Step 1: Create and validate matrix
    P = create_transition_matrix(N)
    validate_matrix(P)
    print("\nTransition Matrix P:")
    print(P)

    # Step 2: Theoretical stationary distribution
    pi_theoretical = compute_stationary_distribution(P)
    print("\nTheoretical Stationary Distribution π:")
    print(pi_theoretical)

    # Step 3: Simulate and get empirical results
    pi_empirical, visits = simulate_markov_chain(P, steps=steps)
    print("\nEmpirical Distribution (from simulation):")
    print(pi_empirical)

    # Step 4: Compare results
    diff = np.abs(pi_empirical - pi_theoretical)
    print("\nDifference (Empirical - Theoretical):")
    print(diff)

    print("\n✅ Average absolute difference:", np.mean(diff))
    print("\n📊 Summary:")
    for i in range(N):
        print(f"State {i}: Theoretical={pi_theoretical[i]:.4f}, Empirical={pi_empirical[i]:.4f}")

    print("\nSimulation complete! 🎯")
    return P, pi_theoretical, pi_empirical


In [ ]:
# -------------------------------------------------------
# 6️⃣ Run the module
# -------------------------------------------------------
if __name__ == "__main__":
    # Run with 5 states
    test_markov_module(N=5, steps=100000)

    # Optional: Run with 6 states
    # test_markov_module(N=6, steps=100000)


🧮 Running Markov Model with 5 states/messages

✅ Transition matrix validated successfully.

Transition Matrix P:
[[0.6 0.4 0.  0.  0. ]
 [0.  0.6 0.4 0.  0. ]
 [0.  0.  0.6 0.4 0. ]
 [0.  0.  0.  0.6 0.4]
 [0.4 0.  0.  0.  0.6]]

Theoretical Stationary Distribution π:
[0.2 0.2 0.2 0.2 0.2]

Empirical Distribution (from simulation):
[0.1989  0.19892 0.19885 0.20301 0.20032]

Difference (Empirical - Theoretical):
[0.0011  0.00108 0.00115 0.00301 0.00032]

✅ Average absolute difference: 0.0013319999999999999

📊 Summary:
State 0: Theoretical=0.2000, Empirical=0.1989
State 1: Theoretical=0.2000, Empirical=0.1989
State 2: Theoretical=0.2000, Empirical=0.1988
State 3: Theoretical=0.2000, Empirical=0.2030
State 4: Theoretical=0.2000, Empirical=0.2003

Simulation complete! 🎯


In [ ]:
# entropy_5_messages.py
import math

def entropy(p, base=2):
    """Compute Shannon entropy for probability list p.
       base=2 returns bits, base=math.e returns nats."""
    if abs(sum(p) - 1.0) > 1e-9:
        raise ValueError("Probabilities must sum to 1.")
    h = 0.0
    for pi in p:
        if pi > 0:
            h -= pi * math.log(pi)  # natural log (nats)
    if base == math.e:
        return h
    return h / math.log(base)

# Example: arbitrary distribution and uniform
P_example = [0.3, 0.2, 0.3, 0.1, 0.1]   # any distribution summing to 1
P_uniform = [1/5.0] * 5

print("Entropy of example distribution:")
print(" - in nats:", entropy(P_example, base=math.e))
print(" - in bits:", entropy(P_example, base=2))

print("\nEntropy of uniform distribution (1/5 each):")
print(" - in nats:", entropy(P_uniform, base=math.e))   # should be ln(5)
print(" - in bits:", entropy(P_uniform, base=2))        # should be log2(5)

# Numeric constants
ln5 = math.log(5)
log2_5 = math.log(5, 2)
print("\nNumeric checks:")
print(" ln(5) =", ln5)
print(" log2(5) =", log2_5)

Entropy of example distribution:
 - in nats: 1.5047882836811908
 - in bits: 2.1709505944546685

Entropy of uniform distribution (1/5 each):
 - in nats: 1.6094379124341005
 - in bits: 2.3219280948873626

Numeric checks:
 ln(5) = 1.6094379124341003
 log2(5) = 2.321928094887362
